### PR TITLE
added DontUseNativeDialog option to QFileDialogs

### PR DESCRIPTION
**Pull request by JStech**
Sometimes on some systems, the dialog to choose a file to load or save doesn't appear. After some searching, I found this change as a fix/workaround.

### CODE REVIEW

**Comment by JStech** [comment]
I don't see this flag used anywhere else in MoveIt, so I'm guessing there's some other way to make this work. I'll keep digging when I get a chance, but I'll leave this open as it's a workaround for now.

**Comment by JStech** [comment]
Well, the flag isn't elsewhere in MoveIt, but those dialogs don't work either. Must be something with my Qt environment or something?

**Comment by JStech** [comment]
I've done some more debugging on this. The QFileDialog only fails to appear when Gazebo is running. There's definitely something Gazebo is doing that's interfering with Qt/Gtk. I'm inclined to go ahead with the `DontUseNativeDialog` workaround.

**Comment by JStech** [comment]
I don't think the root cause of this problem is going to be solved: ros-planning/moveit#2357 hasn't gone anywhere, and I'm out of ideas for debugging it. I think we should merge this since it's a viable workaround.

**Review by felixvd — APPROVED** [review]
I'm fine with this workaround, but I'd link the MoveIt issue in a comment underneath.

**Review by tylerjw — APPROVED** [review]
lgtm, I tried this and it fixes the issue.  Thank you for debugging and fixing this!

**Pull request merged**
